### ISSUE TITLE
A voting animation will stop another running one

### ISSUE THREAD

**Issue by just4fun** [IFS49F/poker#58]
Currently I'm not sure whether it's a bug caused by race condition or misoperation in redux store, but the experience for such behaviour is not good.

Created this issue as bug for tracking.

**Comment by hyjk2000** [comment]
The root cause of this issue is: the `voting` state used to trigger imperative animation is _local_ state, and by _local_ I mean the server is not aware of it (as it should be). Thus, the state update pushed from server won't have this state. That's why when a player voted, the `voting` property of the other players disappears altogether. As a result, all other players' voting animation is terminated.
