### ISSUE TITLE
Website is not working

### ISSUE THREAD

**Issue by hasanb** [IFS49F/poker#93]

**Comment by just4fun** [comment]
hi @hasanb , thanks for using Poker4Fun.

That's because we don't get enough donation to renew domain in last months, which was outdated one week ago. You can check [here](https://github.com/IFS49F/poker#cost) to see cost, and check [here](https://github.com/IFS49F/poker#sponsors) for latest donation.

Just FYI, currently we lost our domain for more than one week, if we need original domain, we need to pay more.

**Comment by just4fun** [comment]
@hasanb Just let you know we renewed our domain and the site is back working now.
